name: Main
on:
  workflow_dispatch:
    inputs:
      os:
        description: >-
         Choose OS(Enter number.)              .
            1=> Windows 
            2=> ubuntu(Linux) 
            3=> MacOs(Apple)
            

        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Welcome  ${{ github.event.inputs.os }}
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          if [[ ${{ github.event.inputs.os }} == "1" || ${{ github.event.inputs.os }} == "window" ]]
          then 
          os = "Windows"
          elif [[ ${{ github.event.inputs.os }} == "2" || ${{ github.event.inputs.os }} == "ubuntu" ||  ${{ github.event.inputs.os }} == "Linux" ]]
          then 
          os="ubuntu"
          elif [[ ${{ github.event.inputs.os }} == "3" || ${{ github.event.inputs.os }} == "macos" ||  ${{ github.event.inputs.os }} == "apple"]]
          then 
          os = "Macos" 
          else
          echo "Invaild Input User From User"
          os = "None"
          fi
          echo "working for Runner $os"

