name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      env:
        NGROK_AUTH_TOKEN: 27boFcDmJMRiu8axi3WJgQo9JwJ_27hpuSYAE4ujGWPJb1UBx
        MAC_USER_PASSWORD: Pass123
        VNC_PASSWORD: Pass123
        MAC_REALNAME: Prajwal
      run: source macos.sh "Pass123" "Pass123" "27boFcDmJMRiu8axi3WJgQo9JwJ_27hpuSYAE4ujGWPJb1UBx" "Prajwal"
    - name: Connecting MacOS with Ngrok to VNC Server
      run: source IP.sh
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
